-- Populate cdm_source with Delphi-2M synthetic data provenance and ETLDelphi transformation metadata.
-- Source: Delphi-2M synthetic patient health trajectories generated by a GPT-2 model trained on UK Biobank.
-- Citation: Shmatko et al., "Learning the natural history of human disease with generative transformers",
--   Nature 647, 248-256 (2025). https://doi.org/10.1038/s41586-025-09529-3
-- Repository: https://github.com/gerstung-lab/Delphi

-- Clear existing row so re-runs update the metadata
DELETE FROM cdm.cdm_source WHERE 1=1;

INSERT INTO cdm.cdm_source (
    cdm_source_name,
    cdm_source_abbreviation,
    cdm_holder,
    source_description,
    source_documentation_reference,
    cdm_etl_reference,
    source_release_date,
    cdm_release_date,
    cdm_version,
    cdm_version_concept_id,
    vocabulary_version
)
SELECT
    'Delphi-2M Synthetic Health Trajectories' AS cdm_source_name,
    'Delphi-2M' AS cdm_source_abbreviation,
    'Gerstung Lab (EMBL / DKFZ)' AS cdm_holder,
    'Synthetic patient health trajectories generated by Delphi-2M, a modified GPT-2 model trained on ~400K UK Biobank patient records. Transformed to OMOP CDM v5.4 by ETLDelphi using a 3-layer pattern (src -> stg -> cdm) in DuckDB. Source tables: enrollment, encounter, provider, death, problem, medication_orders, medication_fulfillment, current_medications, immunization, lab_orders, lab_results, vital_sign, allergy, therapy_orders, therapy_actions. Deterministic IDs; unmapped concepts = 0; reject/QC tables for observability. Citation: Shmatko A, Jung AW, Gaurav K, Brunak S, Mortensen LH, Birney E, Fitzgerald T, Gerstung M. Learning the natural history of human disease with generative transformers. Nature. 2025;647:248-256. doi:10.1038/s41586-025-09529-3' AS source_description,
    'https://doi.org/10.1038/s41586-025-09529-3' AS source_documentation_reference,
    'https://github.com/gerstung-lab/Delphi | ETLDelphi R package (inst/sql/ 00_admin-90_qc)' AS cdm_etl_reference,
    CURRENT_DATE AS source_release_date,
    CURRENT_DATE AS cdm_release_date,
    '5.4' AS cdm_version,
    COALESCE(
        (SELECT concept_id FROM cdm.concept WHERE vocabulary_id = 'CDM' AND concept_class_id = 'CDM' AND concept_code = '5.4' LIMIT 1),
        (SELECT concept_id FROM cdm.concept WHERE vocabulary_id = 'CDM' LIMIT 1)
    ) AS cdm_version_concept_id,
    COALESCE((SELECT vocabulary_version FROM cdm.vocabulary WHERE vocabulary_id = 'None' LIMIT 1), 'Unknown') AS vocabulary_version;
